codecov:
  require_ci_to_pass: yes
  branch: main
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        paths:
          - "app/src/**/*.{js,jsx,ts,tsx}"
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error
  group:
    components:
      pattern: "app/src/components/**/*.{js,jsx,ts,tsx}"
      threshold: auto
    pages:
      pattern: "app/src/pages/**/*.{js,jsx,ts,tsx}"
      threshold: auto
    tests:
      pattern: "app/src/__tests__/**/*.js"
      threshold: auto

ai:
  pr_review: true

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true
