name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy_preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      # AWS credentials
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build
        
      - name: Deploy to S3 preview bucket
        run: |
          # Create preview folder in S3 bucket
          aws s3 sync out/ s3://${{ secrets.S3_BUCKET_NAME }}/pr-${{ env.PR_NUMBER }}/ --delete --cache-control max-age=60
          
          # Output the S3 website URL for verification
          echo "Deployed to: http://${{ secrets.S3_BUCKET_NAME }}.s3-website-${{ env.AWS_REGION }}.amazonaws.com/pr-${{ env.PR_NUMBER }}/"

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Preview deployed! View at:\n\nhttp://${{ secrets.S3_BUCKET_NAME }}.s3-website-${{ env.AWS_REGION }}.amazonaws.com/pr-${process.env.PR_NUMBER}/`
            })
