name: Release and Tag

on:
  push:
    branches: [main]
  create:
    tags:
      - '*'

jobs:
  auto-tag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate tag name
        id: tag_info
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.tag_info.outputs.tag }}
          git push origin ${{ steps.tag_info.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    if: github.event_name == 'create'
    needs: auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for tag ${{ github.ref_name }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
